### ISSUE TITLE
Workflow Suggestions

### ISSUE THREAD

**Issue by amichuda** [gpoore/codebraid#9]
Just wanted to get your thoughts on how you use codebraid for your work.

My current workflow is to write the markdown in VSCode and then run the codebraid command every time I want a new version of my document but it's a bit cumbersome.

What's your set up when you write with codebraid? Do you have any recommendations on software?

**Comment by lordflaron** [comment]
That's a great suggestion! I wrote up a basic script with `inotify` and it works pretty well. 

A vscode extension would be awesome, or at least to have markdown code fencing give python syntax highlighting when writing {.python

**Comment by lordflaron** [comment]
I made a pull request to the vscode grammar so that all supported codebraid languages would have syntax highlighting: 

https://github.com/microsoft/vscode-markdown-tm-grammar/pull/57

You can use my fork if you want with those changes already made:

https://github.com/lordflaron/vscode-markdown-tm-grammar

**Comment by gpoore** [comment]
Syntax highlighting would be great. It might be worth mentioning in your [pull request](https://github.com/microsoft/vscode-markdown-tm-grammar/pull/57/) that this syntax isn't unique to Codebraid. Codebraid just uses Pandoc Markdown, so really what you're requesting is support for Pandoc Markdown (https://pandoc.org/MANUAL.html#fenced-code-blocks).

For general Pandoc Markdown support (not just limited to the languages Codebraid currently supports, which is actually a large number given Jupyter kernels), I think you could just replace all the ``(`{3,}|~{3,})\s*`` (except for the last occurrence, which is for unknown languages) with something like ``(`{3,}|~{3,})\s*(?:\{\s*\.)?`` in the grammar. This wouldn't cover the case of Pandoc's ` ```{#id .language}` syntax, but that probably won't be that common anyway, and having any support would be a major improvement.

**Comment by lordflaron** [comment]
Yes! That seems to make sense, but the grammar file had all those languages
separately so I decided to go along with their format. I'm new to pull
requests (as well this textmate language grammar stuff) so I'm not sure
what's considered appropriate.

In regards to the jupyter kernel support man oh man is that nice. I just
used the Stata kernel and it works perfectly on it. Especially since you
can define separate sessions and have multiple kernels running for one
document.

I want to say thank you again for the great work!
